export const EMAIL_CHANGE_SIGNIN      = 'EMAIL_CHANGE_SIGNIN';
export const PASSWORD_CHANGE_SIGNIN   = 'PASSWORD_CHANGE_SIGNIN';

export const REQUEST_SIGNIN_PENDING = 'REQUEST_SIGNIN_PENDING';
export const REQUEST_SIGNIN_SUCCESS = 'REQUEST_SIGNIN_SUCCESS';
export const REQUEST_SIGNIN_FAILED = 'REQUEST_SIGNIN_FAILED';

export const NAME_CHANGE_REGISTER     = 'NAME_CHANGE_REGISTER';
export const EMAIL_CHANGE_REGISTER    = 'EMAIL_CHANGE_REGISTER';
export const PASSWORD_CHANGE_REGISTER = 'PASSWORD_CHANGE_REGISTER';

export const CHANGE_ROUTE_TO_HOME = 'CHANGE_ROUTE_TO_HOME';
export const CHANGE_ROUTE_TO_SIGNIN = 'CHANGE_ROUTE_TO_SIGNIN';
export const CHANGE_ROUTE_TO_REGISTER = 'CHANGE_ROUTE_TO_REGISTER';